FROM python:alpine
MAINTAINER Zach Bentzinger <bentzingerz@gmail.com>

WORKDIR /database

COPY crontab /etc/crontabs/root
COPY populate.py requirements.txt /project/
RUN pip3 install -r /project/requirements.txt

CMD crond -L /var/log/syslog && python /project/populate.py && tail -f /var/log/syslog
