FROM python:alpine
MAINTAINER bentzingerz@gmail.com

WORKDIR /database

RUN apk update && apk upgrade && apk add rsyslog
COPY populate.py requirements.txt /project/
RUN pip3 install -r /project/requirements.txt

CMD while true; do python /project/populate.py latest; sleep 60; done;
